"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "@/contexts/AuthContext";
import { GoogleOAuthProvider } from "@react-oauth/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GoogleOAuthProvider clientId="854730911868-31nrd8uu3jm0n2a365fguumugu60oeek.apps.googleusercontent.com">
      <AuthContextProvider>
        <html lang="en">
          <body className={`${inter.className} bg-primary text-white`}>
            {children}
          </body>
        </html>
      </AuthContextProvider>
    </GoogleOAuthProvider>
  );
}
